"""
Django settings for SolarMonitor project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from tzlocal import get_localzone
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3i12fo__$(uv4y2k0t^*0y8*jv9w+900@%!whv=dedyf6a)z6w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "daphne",
    "background_task",
    "main",
    #"main.apps.MainConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "accounts",  # new,
    "django_vite_plugin",
    "channels"
    
]

ASGI_APPLICATION = "SolarMonitor.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SolarMonitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    }    
]

WSGI_APPLICATION = 'SolarMonitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
local_tz = get_localzone() 
print("local_tz "+str(local_tz))
TIME_ZONE = str(local_tz)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = (
   BASE_DIR / "static",
)

#STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
print(STATICFILES_DIRS)
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"  # new

LOGGING = {
    'version': 1,
    # Version of logging
    'disable_existing_loggers': False,
 
    'filters':{
        #information regarding filters
    },
 
    'formatters':{
        'Simple_Format':{
            'format': '{asctime} {levelname} in {module} : {message}',
            'style': '{',
        }
    },
 
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': './logs/log_file.log',
            'maxBytes' :4*1024 * 1024,
            'backupCount' : 10,
            'formatter':'Simple_Format'
        },'file_error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': './logs/log_file_error.log',
            'maxBytes' :4*1024 * 1024,
            'backupCount' : 10,
            'formatter':'Simple_Format'
        },'file_imdb': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': './logs/log_file_imdb.log',
            'maxBytes' :4*1024 * 1024,
            'backupCount' : 10,
            'formatter':'Simple_Format'
        },
#         'statuslogging':{
#             'level': 'INFO',
#             'class': 'logging.handlers.RotatingFileHandler',
#             'filename': './logs/log_file_status.log',
#             'maxBytes' : 4 * 1024,
#             'backupCount' : 1,
#             'formatter':'Simple_Format'
#         },
        'file_request': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': './logs/log_file_request.log',
            'maxBytes' :4*1024 * 1024,
            'backupCount' : 20,
            'formatter':'Simple_Format'
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter':'Simple_Format'
        },
    },
 
    'loggers': {
        'django': {
            'handlers': ['file', 'console','file_error'],
            'level': 'DEBUG',
        },
        'django_imdb': {
            'handlers': ['file_imdb'],
            'level': 'DEBUG',
        },
        'django.request': {
            'handlers': ['file_request'],
            'level': 'DEBUG',
        },
    },
}