# Generated by Django 5.1.1 on 2025-01-20 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(max_length=100, validators=[django.core.validators.URLValidator()])),
                ('unit', models.CharField(default='C', max_length=100)),
                ('sensor_type', models.CharField(default='OneWire', max_length=100)),
                ('key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PowlandValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField()),
                ('OperationMode', models.IntegerField()),
                ('EffectiveMainsVoltage', models.FloatField()),
                ('MainsFrequency', models.FloatField()),
                ('AverageMainsPower', models.FloatField()),
                ('EffectiveInverterVoltage', models.FloatField()),
                ('EffectiveInverterCurrent', models.FloatField()),
                ('InverterFrequency', models.FloatField()),
                ('AverageInverterPower', models.FloatField()),
                ('InverterChargingPower', models.FloatField()),
                ('OutputEffectiveVoltage', models.FloatField()),
                ('OutputEffectiveCurrent', models.FloatField()),
                ('OutputFrequency', models.FloatField()),
                ('OutputActivePower', models.FloatField()),
                ('OutputApparentPower', models.FloatField()),
                ('BatteryAverageVoltage', models.FloatField()),
                ('BatteryAverageCurrent', models.FloatField()),
                ('BatteryAveragePower', models.FloatField()),
                ('PVAverageVoltage', models.FloatField()),
                ('PVAverageCurrent', models.FloatField()),
                ('PVAveragePower', models.FloatField()),
                ('PVChargingAveragePower', models.FloatField()),
                ('LoadPercentage', models.FloatField()),
                ('DCDCTemperature', models.FloatField()),
                ('InverterTemperature', models.FloatField()),
                ('BatteryStateOfCharge', models.FloatField()),
                ('BatteryAverageCurrentFlow', models.FloatField()),
                ('InverterChargingAverageCurrent', models.FloatField()),
                ('PVChargingAverageCurrent', models.FloatField()),
                ('AverageInverterEnergy', models.FloatField()),
                ('AverageMainsEnergy', models.FloatField()),
                ('BatteryAverageEnergy', models.FloatField()),
                ('InverterChargingEnergy', models.FloatField()),
                ('OutputActiveEnergy', models.FloatField()),
                ('OutputApparentEnergy', models.FloatField()),
                ('PVAverageEnergy', models.FloatField()),
                ('PVChargingAverageEnergy', models.FloatField()),
                ('AverageInverterEnergyTotal', models.FloatField()),
                ('AverageMainsEnergyTotal', models.FloatField()),
                ('BatteryAverageEnergyTotal', models.FloatField()),
                ('InverterChargingEnergyTotal', models.FloatField()),
                ('OutputActiveEnergyTotal', models.FloatField()),
                ('OutputApparentEnergyTotal', models.FloatField()),
                ('PVAverageEnergyTotal', models.FloatField()),
                ('PVChargingAverageEnergyTotal', models.FloatField()),
                ('EnergyFromFullCharge', models.FloatField()),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inverter')),
            ],
        ),
        migrations.CreateModel(
            name='PZMValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('power', models.FloatField()),
                ('energy', models.FloatField()),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inverter')),
            ],
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensor')),
            ],
        ),
    ]
