# Generated by Django 5.1.1 on 2025-01-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='type',
            field=models.CharField(default='POWLAND', max_length=100),
        ),
    ]
