# Generated by Django 5.1.1 on 2024-10-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(default='OneWire', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(default='C', max_length=100),
        ),
    ]
