# Generated by Django 5.1.1 on 2024-10-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sensor_type_alter_sensor_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='type',
            new_name='sensor_type',
        ),
    ]
