# Generated by Django 5.1.1 on 2025-01-21 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inverter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='host',
            field=models.CharField(max_length=100, validators=[django.core.validators.URLValidator()]),
        ),
    ]
