# Generated by Django 5.1.1 on 2024-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_type_sensor_sensor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inverter',
            old_name='ip_location',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='ip_location',
            new_name='host',
        ),
        migrations.AddField(
            model_name='sensor',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
